site_name: Documentación Sprint 5 - Equipo 4
site_description: Documentación técnica del Sprint 5 - DAW IES Enric Valor
site_author: Kirsha L. Morán Martínez, Lukas Tamulaitis Volkov

theme:
  name: material

nav:
  - Introducción: index.md
  - DIW: diw.md
  - DWEC: dwec.md
  - Proyecto Intermodular: proyecto.md
  - Conclusión: conclusion.md